"""Merge validated QC corrections into a book's ``qc_fixes.toml``.

The file's TOML schema is::

    [phrase]
    "find text" = "replace text"

The writer preserves any human-authored entries (anything outside the
auto-generated block) and rewrites only the auto-generated section
between the marker comments::

    # AUTO QC START -- generated by `quire qc`; do not edit between markers
    ... auto entries ...
    # AUTO QC END

If no auto block exists yet, one is appended at the end of the file.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from ..io_utils import atomic_write_text
from .models import Correction

_AUTO_START = "# AUTO QC START -- generated by `quire qc`; do not edit between markers"
_AUTO_END = "# AUTO QC END"

_AUTO_BLOCK_RE = re.compile(
    re.escape(_AUTO_START) + r".*?" + re.escape(_AUTO_END) + r"\s*",
    re.S,
)


@dataclass
class WriteResult:
    """Outcome of a writer call."""

    written: int  # number of auto entries finally on disk
    added: int  # newly-added entries vs the prior auto block
    preserved_human: int  # count of human-authored phrases left alone
    path: Path


def _escape_toml_double_quoted(s: str) -> str:
    """Escape a string for a TOML double-quoted literal."""
    out: list[str] = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return "".join(out)


def _read_existing(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text("utf-8")
    except OSError:
        return ""


def _parse_human_phrases(body: str) -> dict[str, str]:
    """Best-effort extract phrases outside the auto block.

    This is intentionally not a full TOML parser. We only need to know
    the set of ``find`` keys that exist so we can avoid emitting an
    auto entry that would shadow a human one in the merged file.
    """
    stripped = _AUTO_BLOCK_RE.sub("", body)
    out: dict[str, str] = {}
    for m in re.finditer(
        r'^\s*"((?:[^"\\]|\\.)+)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*$',
        stripped,
        re.M,
    ):
        out[m.group(1)] = m.group(2)
    return out


def _existing_auto_phrases(body: str) -> dict[str, str]:
    m = _AUTO_BLOCK_RE.search(body)
    if not m:
        return {}
    inner = m.group(0)
    out: dict[str, str] = {}
    for line_match in re.finditer(
        r'^\s*"((?:[^"\\]|\\.)+)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*$',
        inner,
        re.M,
    ):
        out[line_match.group(1)] = line_match.group(2)
    return out


def _ensure_phrase_header(body_without_auto: str) -> str:
    """Make sure the residual body contains a ``[phrase]`` table.

    If the human section is empty or lacks the header, the auto block
    will provide one. Otherwise we trust the human file.
    """
    return body_without_auto


def _build_auto_block(phrases: dict[str, str]) -> str:
    """Format the auto-generated block. Phrases are emitted sorted."""
    lines = [_AUTO_START]
    for find in sorted(phrases.keys()):
        replace = phrases[find]
        f_esc = _escape_toml_double_quoted(find)
        r_esc = _escape_toml_double_quoted(replace)
        lines.append(f'"{f_esc}" = "{r_esc}"')
    lines.append(_AUTO_END)
    lines.append("")  # trailing newline
    return "\n".join(lines)


def merge_corrections(
    path: Path,
    corrections: list[Correction],
    *,
    preserve_human: bool = True,
) -> WriteResult:
    """Merge ``corrections`` into the auto block of ``path``.

    Returns a :class:`WriteResult` summarizing what changed. Writes
    atomically. If ``preserve_human`` is True (default), corrections
    whose ``find`` already appears as a human-authored phrase are
    dropped (the human entry wins).
    """
    existing = _read_existing(path)
    human = _parse_human_phrases(existing) if preserve_human else {}
    prior_auto = _existing_auto_phrases(existing)

    new_phrases: dict[str, str] = {}
    for c in corrections:
        if c.find in human:
            continue  # human override wins
        # Last-write wins within the same run.
        new_phrases[c.find] = c.replace

    added = sum(1 for k in new_phrases if k not in prior_auto)

    body_without_auto = _AUTO_BLOCK_RE.sub("", existing).rstrip()
    needs_header = "[phrase]" not in body_without_auto
    parts: list[str] = []
    if body_without_auto:
        parts.append(body_without_auto)
        parts.append("")
    if needs_header:
        parts.append("[phrase]")
    parts.append(_build_auto_block(new_phrases))
    output = "\n".join(parts)
    if not output.endswith("\n"):
        output += "\n"

    atomic_write_text(path, output)
    return WriteResult(
        written=len(new_phrases),
        added=added,
        preserved_human=len(human),
        path=path,
    )
